name: Lint Check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        run: npm ci

      - name: HTML check
        run: npm run lint:html

      - name: JS check
        run: npm run lint:js

      - name: CSS check
        run: npm run lint:css